[2025-04-11T03:58:01.242+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T03:58:01.264+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T03:58:01.274+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T03:58:01.276+0000] {taskinstance.py:2856} INFO - Starting attempt 18 of 19
[2025-04-11T03:58:01.289+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): data_loading> on 2025-04-10 00:00:00+00:00
[2025-04-11T03:58:01.297+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2174) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T03:58:01.299+0000] {standard_task_runner.py:72} INFO - Started process 2177 to run task
[2025-04-11T03:58:01.298+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'data_loading', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_workshop.py', '--cfg-path', '/tmp/tmpf5wqakby']
[2025-04-11T03:58:01.300+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask data_loading
[2025-04-11T03:58:01.349+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [running]> on host c97e2588350c
[2025-04-11T03:58:02.775+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='18' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-11T03:58:02.777+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-11T03:58:03.915+0000] {load.py:25} INFO - Loading clean data to the database.
[2025-04-11T03:58:03.916+0000] {db_operations.py:21} INFO - Connecting to database database workshop_2 , user workshop2, host dpg-cvrve4q4d50c73d7h19g-a.ohio-postgres.render.com, port 5432, password O0mkYGKfG2jhnjOCxKKnhDE2dhLgxaEg
[2025-04-11T03:58:06.213+0000] {db_operations.py:51} INFO - Attempting to create/load table merged_data from Pandas DataFrame
[2025-04-11T03:58:08.125+0000] {db_operations.py:55} INFO - Table merged_data does not exist. Creating it...
[2025-04-11T03:58:08.975+0000] {db_operations.py:69} INFO - Table schema for merged_data created.
[2025-04-11T03:59:33.876+0000] {db_operations.py:73} INFO - Data successfully loaded into table merged_data.
[2025-04-11T03:59:33.924+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T03:59:33.934+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-11T03:59:33.935+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=data_loading, run_id=scheduled__2025-04-10T00:00:00+00:00, execution_date=20250410T000000, start_date=20250411T035801, end_date=20250411T035933
[2025-04-11T03:59:34.006+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-04-11T03:59:34.022+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-11T03:59:34.026+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
