[2025-04-11T03:12:12.964+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T03:12:12.981+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T03:12:12.991+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T03:12:12.992+0000] {taskinstance.py:2856} INFO - Starting attempt 9 of 10
[2025-04-11T03:12:13.005+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): data_loading> on 2025-04-10 00:00:00+00:00
[2025-04-11T03:12:13.012+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1508) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T03:12:13.014+0000] {standard_task_runner.py:72} INFO - Started process 1512 to run task
[2025-04-11T03:12:13.015+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'data_loading', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_workshop.py', '--cfg-path', '/tmp/tmp0li78h6l']
[2025-04-11T03:12:13.020+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask data_loading
[2025-04-11T03:12:13.060+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.data_loading scheduled__2025-04-10T00:00:00+00:00 [running]> on host c97e2588350c
[2025-04-11T03:12:13.935+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-11T03:12:13.936+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-11T03:12:14.784+0000] {etl.py:82} ERROR - Error loading data to database: loading_merged_data() missing 1 required positional argument: 'table_name'
[2025-04-11T03:12:14.824+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T03:12:14.836+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-11T03:12:14.837+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=data_loading, run_id=scheduled__2025-04-10T00:00:00+00:00, execution_date=20250410T000000, start_date=20250411T031212, end_date=20250411T031214
[2025-04-11T03:12:14.875+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-04-11T03:12:14.901+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-11T03:12:14.904+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
