[2025-04-11T04:13:51.325+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T04:13:51.339+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.data_storing scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T04:13:51.347+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.data_storing scheduled__2025-04-10T00:00:00+00:00 [queued]>
[2025-04-11T04:13:51.349+0000] {taskinstance.py:2856} INFO - Starting attempt 18 of 19
[2025-04-11T04:13:51.357+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): data_storing> on 2025-04-10 00:00:00+00:00
[2025-04-11T04:13:51.361+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=135) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-11T04:13:51.362+0000] {standard_task_runner.py:72} INFO - Started process 138 to run task
[2025-04-11T04:13:51.364+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'data_storing', 'scheduled__2025-04-10T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/dag_for_workshop.py', '--cfg-path', '/tmp/tmpgppb4lqf']
[2025-04-11T04:13:51.366+0000] {standard_task_runner.py:105} INFO - Job 79: Subtask data_storing
[2025-04-11T04:13:51.946+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.data_storing scheduled__2025-04-10T00:00:00+00:00 [running]> on host d3a7fa6095e6
[2025-04-11T04:13:53.260+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='data_storing' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='18' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-10T00:00:00+00:00'
[2025-04-11T04:13:53.262+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-11T04:13:54.285+0000] {store.py:38} INFO - Starting Google Drive authentication process.
[2025-04-11T04:13:54.288+0000] {store.py:48} INFO - Using saved credentials.
[2025-04-11T04:13:54.289+0000] {store.py:59} INFO - Google Drive authentication completed successfully.
[2025-04-11T04:13:54.290+0000] {store.py:83} INFO - Storing merged_data on Google Drive.
[2025-04-11T04:14:02.583+0000] {store.py:97} INFO - File merged_data uploaded successfully.
[2025-04-11T04:14:02.637+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-11T04:14:02.646+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-11T04:14:02.647+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=data_storing, run_id=scheduled__2025-04-10T00:00:00+00:00, execution_date=20250410T000000, start_date=20250411T041351, end_date=20250411T041402
[2025-04-11T04:14:02.673+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-04-11T04:14:02.686+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-11T04:14:02.690+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
